# PostgREST configuration file
# For more options, see: https://postgrest.org/en/stable/references/configuration.html

# The standard connection URI to the database
db-uri = "$(PGRST_DB_URI)"

# The database schema to expose to REST clients
db-schema = "public"

# The database role to use when no client authentication is provided
db-anon-role = "$(PGRST_DB_ANON_ROLE)"

# The base URL for the API
# server-host = "0.0.0.0"
# server-port = 3000

# Database pool size
# db-pool = 10
