# Generated by Django 5.2.4 on 2026-03-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetManagementCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_th",
                    models.CharField(max_length=255, verbose_name="ชื่อ บลจ. (ไทย)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="ชื่อ บลจ. (อังกฤษ)"),
                ),
                ("short_name", models.CharField(max_length=50, unique=True)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ชื่อย่อกองทุน"
                    ),
                ),
                ("name_th", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                (
                    "fund_category",
                    models.CharField(
                        help_text="เช่น Global Equity, Fixed Income", max_length=100
                    ),
                ),
                (
                    "risk_level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5"),
                            (6, "Level 6"),
                            (7, "Level 7"),
                            (8, "Level 8"),
                        ]
                    ),
                ),
                (
                    "is_dividend",
                    models.BooleanField(default=False, verbose_name="นโยบายปันผล"),
                ),
                (
                    "management_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% ต่อปี",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_expense_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="TER (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("sharpe_ratio", models.FloatField(blank=True, null=True)),
                ("alpha", models.FloatField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("max_drawdown", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funds",
                        to="fundDecision.assetmanagementcompany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insight_type", models.CharField(max_length=50)),
                ("content", models.TextField(verbose_name="บทวิเคราะห์จาก AI")),
                ("confidence_score", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                (
                    "model_version",
                    models.CharField(
                        help_text="ชื่อรุ่น AI เช่น GPT-4o, Claude-3", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="fundDecision.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FundAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_deviation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ค่าความผันผวน"
                    ),
                ),
                ("treynor_ratio", models.FloatField(blank=True, null=True)),
                ("sortino_ratio", models.FloatField(blank=True, null=True)),
                ("information_ratio", models.FloatField(blank=True, null=True)),
                (
                    "capture_ratio_up",
                    models.FloatField(
                        blank=True, help_text="Upside Capture", null=True
                    ),
                ),
                (
                    "capture_ratio_down",
                    models.FloatField(
                        blank=True, help_text="Downside Capture", null=True
                    ),
                ),
                ("raw_data_for_ai", models.JSONField(blank=True, null=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="fundDecision.fund",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HoldingAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=255)),
                ("proportion", models.FloatField(help_text="สัดส่วนการถือครอง (%)")),
                ("as_of_date", models.DateField(help_text="ข้อมูล ณ วันที่")),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="fundDecision.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-proportion"],
            },
        ),
        migrations.CreateModel(
            name="FundNAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("nav", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("percent_change", models.FloatField(blank=True, null=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_history",
                        to="fundDecision.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("fund", "date")},
            },
        ),
    ]
