# Generated by Django 5.2.12 on 2026-03-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='ticker',
            new_name='fundCode',
        ),
    ]
