# Generated by Django 5.2.12 on 2026-03-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0002_rename_ticker_fund_fundcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('related_sectors', models.JSONField(blank=True, help_text='กลุ่มอุตสาหกรรมที่เกี่ยวข้อง เช่น Tech, Energy', null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='-1 (ร้ายสุด) ถึง 1 (ดีสุด)', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI สรุปสั้นๆ ว่าข่าวนี้ส่งผลอย่างไร')),
                ('impact_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], max_length=20, null=True)),
                ('related_funds', models.ManyToManyField(related_name='related_news', to='fundDecision.fund')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
