# Generated by Django 5.2.12 on 2026-03-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0003_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fact_sheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fact_sheets/'),
        ),
        migrations.AddField(
            model_name='fund',
            name='fact_sheet_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='last_updated_ffs',
            field=models.DateField(null=True, verbose_name='วันที่อัปเดตเอกสารล่าสุด'),
        ),
    ]
