# Generated by Django 5.2.12 on 2026-03-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0004_fund_fact_sheet_pdf_fund_fact_sheet_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoldingAsset',
            new_name='FundHoldingAsset',
        ),
        migrations.RenameModel(
            old_name='Fund',
            new_name='FundInfo',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='impact_level',
            new_name='ai_impact_level',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='sentiment_score',
            new_name='ai_sentiment_score',
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='sentiment_impact_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='-1 (ร้ายสุด) ถึง 1 (ดีสุด)', null=True),
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='sentiment_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fm_impact_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fm_sentiment_score',
            field=models.FloatField(blank=True, help_text='-1 (ร้ายสุด) ถึง 1 (ดีสุด)', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fm_summary',
            field=models.TextField(blank=True, help_text='AI สรุปสั้นๆ ว่าข่าวนี้ส่งผลอย่างไร'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fund_supervisor_approve',
            field=models.BooleanField(default=False, help_text='ผู้จัดการกองทุนอนุมัติ'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fund_supervisor_approve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fund_supervisor_approve_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fund_supervisor_comment',
            field=models.TextField(blank=True, help_text='ผู้จัดการกองทุนอนุมัติ', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_status',
            field=models.BooleanField(default=False, help_text='เผยแพร่'),
        ),
        migrations.AlterField(
            model_name='fundanalysis',
            name='fund',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_analysis', to='fundDecision.fundinfo'),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='fundDecision.fundinfo'),
        ),
        migrations.AlterField(
            model_name='fundholdingasset',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='fundDecision.fundinfo'),
        ),
        migrations.AlterField(
            model_name='fundnav',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='fundDecision.fundinfo'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='related_funds',
            field=models.ManyToManyField(related_name='related_news', to='fundDecision.fundinfo'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
