# Generated by Django 5.2.12 on 2026-03-16 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0005_rename_holdingasset_fundholdingasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
