# Generated by Django 5.2.12 on 2026-03-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0006_fundanalysis_created_at_fundanalysis_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundanalysis',
            name='createBy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='updateBy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fundanalysis',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_analysis', to='fundDecision.fundinfo'),
        ),
    ]
