# Generated by Django 5.2.12 on 2026-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0007_fundanalysis_createby_fundanalysis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='related_funds',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_news', to='fundDecision.fundinfo'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='related_sectors',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Energy', 'Energy'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Consumer', 'Consumer'), ('Industrials', 'Industrials'), ('Materials', 'Materials'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate'), ('Telecommunications', 'Telecommunications')], max_length=20, null=True),
        ),
    ]
