# Generated by Django 5.2.12 on 2026-03-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0008_alter_newsarticle_related_funds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='related_sectors',
            field=models.JSONField(blank=True, default=list, help_text='List of sectors: Tech, Energy, Healthcare, etc.'),
        ),
    ]
