# Generated by Django 5.2.12 on 2026-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0009_alter_newsarticle_related_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='relate_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
