# Generated by Django 5.2.4 on 2026-03-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundDecision", "0010_newsarticle_relate_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
