# Generated by Django 5.2.12 on 2026-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0011_newsarticle_author_newsarticle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
