# Generated by Django 5.2.13 on 2026-04-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0012_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundnav',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fundinfo',
            name='amc',
        ),
        migrations.RemoveField(
            model_name='fundholdingasset',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='fundanalysis',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='fundnav',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='related_funds',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='fund',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='fundCode',
            field=models.CharField(default='', max_length=20, verbose_name='ชื่อย่อกองทุน'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundanalysis',
            name='fundCode',
            field=models.CharField(default='', max_length=20, verbose_name='ชื่อย่อกองทุน'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssetManagementCompany',
        ),
        migrations.DeleteModel(
            name='FundHoldingAsset',
        ),
        migrations.DeleteModel(
            name='FundNAV',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='related_funds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อย่อกองทุน'),
        ),
        migrations.DeleteModel(
            name='FundInfo',
        ),
    ]
