# Generated by Django 5.2.13 on 2026-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0013_remove_fundinfo_amc_remove_fundholdingasset_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='ai_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='relate_product',
            field=models.JSONField(blank=True, default=list, help_text='List of products: MF, PF, Bond'),
        ),
    ]
