# Generated by Django 5.2.4 on 2026-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundDecision", "0014_newsarticle_ai_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="ai_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
