# Generated by Django 5.2.4 on 2026-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundDecision", "0015_alter_newsarticle_ai_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundFactSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fund_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสกองทุน"
                    ),
                ),
                (
                    "fund_name_th",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ชื่อกองทุนภาษาไทย"
                    ),
                ),
                (
                    "sec_proj_id",
                    models.CharField(
                        blank=True, help_text="ID จาก SEC API", max_length=50
                    ),
                ),
                (
                    "risk_level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ระดับความเสี่ยง (1-8)"
                    ),
                ),
                (
                    "fund_category",
                    models.CharField(
                        blank=True,
                        help_text="เช่น Equity Large-Cap, Global Bond",
                        max_length=100,
                    ),
                ),
                (
                    "investment_strategy",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("Passive", "Passive")],
                        max_length=50,
                    ),
                ),
                (
                    "holdings_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="ข้อมูลการถือครองหุ้น 5-10 อันดับแรก",
                    ),
                ),
                (
                    "sector_allocation",
                    models.JSONField(
                        blank=True,
                        help_text="สัดส่วนกลุ่มอุตสาหกรรม เช่น พลังงาน 20%, แบงก์ 15%",
                        null=True,
                    ),
                ),
                ("is_hedged", models.BooleanField(default=False)),
                (
                    "hedging_policy",
                    models.TextField(
                        blank=True, help_text="นโยบายป้องกันความเสี่ยงค่าเงินแบบละเอียด"
                    ),
                ),
                (
                    "currency_hedging",
                    models.CharField(
                        blank=True,
                        help_text="None/Partial/Fully/Discretionary",
                        max_length=50,
                    ),
                ),
                ("benchmark", models.CharField(blank=True, max_length=255)),
                (
                    "dividend_policy",
                    models.BooleanField(default=False, verbose_name="นโยบายจ่ายปันผล"),
                ),
                (
                    "factsheet_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="fact_sheets/",
                        verbose_name="ไฟล์ Fund Fact Sheet (PDF)",
                    ),
                ),
                (
                    "as_of_date",
                    models.DateField(
                        blank=True,
                        help_text="ข้อมูลใน Fact Sheet นี้เป็นข้อมูล ณ วันที่เท่าไหร่",
                        null=True,
                    ),
                ),
                (
                    "ai_analysis_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("ai_error_message", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fund Fact Sheet",
                "verbose_name_plural": "Fund Fact Sheets",
                "ordering": ["-as_of_date", "-created_at"],
            },
        ),
    ]
