# Generated by Django 5.2.4 on 2026-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundDecision", "0016_fundfactsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundfactsheet",
            name="factsheet_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="ลิงก์ Fund Fact Sheet (URL)",
            ),
        ),
    ]
