# Generated by Django 5.2.13 on 2026-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0017_fundfactsheet_factsheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundfactsheet',
            name='json_raw',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON Raw'),
        ),
    ]
