# Generated by Django 5.2.13 on 2026-04-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0018_fundfactsheet_json_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundfactsheet',
            old_name='json_raw',
            new_name='prompt_val',
        ),
    ]
