# Generated by Django 5.2.13 on 2026-04-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0020_alter_fundfactsheet_benchmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundfactsheet',
            name='fund_category',
            field=models.TextField(blank=True, help_text='เช่น Equity Large-Cap, Global Bond'),
        ),
    ]
