# Generated by Django 5.2.13 on 2026-04-22 06:51

from pgvector.django import VectorExtension
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundDecision', '0021_alter_fundfactsheet_fund_category'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='FundDocumentChunk',

            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=20, verbose_name='รหัสกองทุน')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='Vector Embedding')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='เลขหน้า')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fund Document Chunk',
                'verbose_name_plural': 'Fund Document Chunks',
            },
        ),
    ]
