# Generated by Django 5.2.4 on 2026-03-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ICLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compCode", models.CharField(max_length=15)),
                ("IC_license", models.CharField(max_length=10)),
                ("fullName", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "IC License",
                "verbose_name_plural": "IC Licenses",
                "unique_together": {("compCode", "IC_license")},
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compCode", models.CharField(max_length=13)),
                ("custCode", models.CharField(max_length=13)),
                ("fullNameEn", models.CharField(max_length=100)),
                ("fullNameTh", models.CharField(max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("compCode", "custCode")},
            },
        ),
        migrations.CreateModel(
            name="InvestorAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compCode", models.CharField(max_length=13)),
                ("accountID", models.CharField(max_length=15)),
                ("openDate", models.DateField(blank=True, null=True)),
                (
                    "IC_license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="invest.iclicense",
                    ),
                ),
                (
                    "custCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="invest.investor",
                    ),
                ),
            ],
            options={
                "unique_together": {("compCode", "accountID")},
            },
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compCode", models.CharField(max_length=15)),
                ("fundCode", models.CharField(max_length=30)),
                ("unitBalance", models.DecimalField(decimal_places=4, max_digits=18)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "averageCost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                ("NAV", models.DecimalField(decimal_places=4, max_digits=13)),
                ("NAVdate", models.DateField()),
                (
                    "accountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="invest.investoraccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("compCode", "accountID", "fundCode")},
            },
        ),
    ]
