# Generated by Django 5.2.12 on 2026-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='projects',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='status',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
