# Generated by Django 5.2.12 on 2026-03-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_investor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=13)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('FromDate', models.DateField(blank=True, null=True)),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(max_length=50)),
                ('custCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_accounts', to='invest.investor')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateFundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=13)),
                ('accountID', models.CharField(max_length=15)),
                ('openDate', models.DateField(blank=True, null=True)),
                ('IC_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_fund_accounts', to='invest.iclicense')),
                ('custCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_fund_accounts', to='invest.investor')),
            ],
            options={
                'unique_together': {('compCode', 'accountID')},
            },
        ),
        migrations.CreateModel(
            name='PrivateFundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=15)),
                ('fundCode', models.CharField(max_length=30)),
                ('unitBalance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('averageCost', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('NAV', models.DecimalField(decimal_places=4, max_digits=13)),
                ('NAVdate', models.DateField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_fund_balances', to='invest.privatefundaccount')),
            ],
            options={
                'unique_together': {('compCode', 'accountID', 'fundCode')},
            },
        ),
    ]
