# Generated by Django 5.2.12 on 2026-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_bondaccount_privatefundaccount_privatefundbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondaccount',
            name='bondCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
