# Generated by Django 5.2.12 on 2026-03-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_bondaccount_bondcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAOrderReferenceNo', models.CharField(blank=True, max_length=30, null=True)),
                ('TransactionDateTime', models.DateTimeField()),
                ('AMCCode', models.CharField(max_length=15)),
                ('UnitholderID', models.CharField(max_length=15)),
                ('TransactionCode', models.CharField(max_length=3)),
                ('FundCode', models.CharField(blank=True, max_length=30, null=True)),
                ('OverrideRiskProfileFlag', models.CharField(max_length=1)),
                ('RedemptionType', models.CharField(blank=True, max_length=4, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('Unit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('EffectiveDate', models.DateField()),
                ('PaymentType', models.CharField(max_length=8)),
                ('BankCode', models.CharField(blank=True, max_length=4, null=True)),
                ('BankAccount', models.CharField(blank=True, max_length=20, null=True)),
                ('ICLicense', models.CharField(max_length=10)),
                ('BranchNo', models.CharField(max_length=5)),
                ('Channel', models.CharField(max_length=3)),
                ('TransactionID', models.CharField(max_length=17, unique=True)),
                ('Status', models.CharField(max_length=10)),
                ('AMCOrderReferenceNo', models.CharField(blank=True, max_length=30, null=True)),
                ('AllotmentDate', models.DateField(blank=True, null=True)),
                ('AllottedNAV', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('AllottedAmount', models.DecimalField(blank=True, decimal_places=4, max_digits=21, null=True)),
                ('AllotedUnit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('Fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('WithholdingTax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('VAT', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('BrokerageFee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('AMCPayDate', models.DateField(blank=True, null=True)),
                ('RejectReason', models.CharField(blank=True, max_length=50, null=True)),
                ('ICCode', models.CharField(blank=True, max_length=10, null=True)),
                ('BrokerageFeeVAT', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('NAVDate', models.DateField(blank=True, null=True)),
                ('CollateralAccount', models.CharField(blank=True, max_length=20, null=True)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_transactions', to='invest.investoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=15)),
                ('fundCode', models.CharField(max_length=30)),
                ('unitBalance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('averageCost', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('NAV', models.DecimalField(decimal_places=4, max_digits=13)),
                ('NAVdate', models.DateField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_balances', to='invest.investoraccount')),
            ],
            options={
                'unique_together': {('compCode', 'accountID', 'fundCode', 'NAVdate')},
            },
        ),
        migrations.CreateModel(
            name='PerformancePrivateFundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compCode', models.CharField(max_length=15)),
                ('fundCode', models.CharField(max_length=30)),
                ('unitBalance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('averageCost', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('NAV', models.DecimalField(decimal_places=4, max_digits=13)),
                ('NAVdate', models.DateField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_private_fund_balances', to='invest.privatefundaccount')),
            ],
            options={
                'unique_together': {('compCode', 'accountID', 'fundCode', 'NAVdate')},
            },
        ),
    ]
