# Generated by Django 5.2.12 on 2026-03-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_mftransaction_performanceaccountbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftransaction',
            name='AccountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mf_transactions', to='invest.investoraccount'),
        ),
    ]
