# Generated by Django 5.2.12 on 2026-03-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0007_alter_mftransaction_accountid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformanceAccountBalance',
            new_name='PerformanceMFAccountBalance',
        ),
    ]
