# Generated by Django 5.2.12 on 2026-03-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_rename_amcorderreferenceno_mftransaction_amcorderreferenceno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mftransaction',
            old_name='AllotmentDate',
            new_name='allotmentDate',
        ),
    ]
