# Generated by Django 5.2.12 on 2026-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_rename_allotmentdate_mftransaction_allotmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftransaction',
            name='transactionDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
