# Generated by Django 5.2.12 on 2026-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0011_alter_mftransaction_transactiondatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemfaccountbalance',
            name='marketValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='performancemfaccountbalance',
            name='roi_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='performancemfaccountbalance',
            name='unrealizedGain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
