# Generated by Django 5.2.12 on 2026-03-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0012_performancemfaccountbalance_marketvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemfaccountbalance',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
