# Generated by Django 5.2.12 on 2026-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0013_performancemfaccountbalance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='marketValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='roi_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='unrealizedGain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
