# Generated by Django 5.2.12 on 2026-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0014_performanceprivatefundbalance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemfaccountbalance',
            name='marketValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='performancemfaccountbalance',
            name='roi_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='performancemfaccountbalance',
            name='unrealizedGain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprivatefundbalance',
            name='marketValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprivatefundbalance',
            name='roi_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprivatefundbalance',
            name='unrealizedGain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
