# Generated by Django 5.2.12 on 2026-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0015_alter_performancemfaccountbalance_marketvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='business_date_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
