# Generated by Django 5.2.12 on 2026-03-13 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0017_marketing_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoraccount',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
