# Generated by Django 5.2.12 on 2026-03-13 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0018_investoraccount_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketing',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='marketing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketing',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Marketing Staff'), ('GROUP_LEADER', 'Group Leader'), ('MANAGER', 'Manager')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='marketing',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='invest.marketing'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='ExternalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentCode', models.CharField(max_length=20, unique=True)),
                ('fullName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_investors', to='invest.externalagent'),
        ),
        migrations.CreateModel(
            name='MarketingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100, verbose_name='ชื่อกลุ่ม/ทีม')),
                ('description', models.TextField(blank=True, null=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='invest.marketing')),
            ],
        ),
        migrations.AddField(
            model_name='marketing',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='invest.marketinggroup'),
        ),
    ]
