# Generated by Django 5.2.12 on 2026-03-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0019_alter_marketing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoraccount',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_account', to='invest.externalagent'),
        ),
    ]
