# Generated by Django 5.2.12 on 2026-03-13 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0020_alter_investoraccount_referred_by_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondaccount',
            name='Status',
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bond_accounts', to='invest.marketing'),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_bond_account', to='invest.externalagent'),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='gain_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='gain_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='pct_by_port',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='performanceprivatefundbalance',
            name='sis_capital_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='privatefundaccount',
            name='fundType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatefundaccount',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_pf_account', to='invest.externalagent'),
        ),
        migrations.AddField(
            model_name='privatefundaccount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mf_accounts', to='invest.marketing'),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_mfaccount', to='invest.externalagent'),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='privatefundaccount',
            name='marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_accounts', to='invest.marketing'),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
