# Generated by Django 5.2.12 on 2026-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0021_remove_bondaccount_status_bondaccount_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondaccount',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bondaccount',
            old_name='FromDate',
            new_name='fromDate',
        ),
        migrations.RenameField(
            model_name='bondaccount',
            old_name='ToDate',
            new_name='maturityDate',
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='bondSymbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='issuer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='maturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='maturityStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='maturityType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='paymentAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='paymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='paymentStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='paymentType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bondaccount',
            name='toDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
