# Generated by Django 5.2.12 on 2026-03-13 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0022_rename_amount_bondaccount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bondaccount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Matured', 'Matured'), ('Default', 'Default'), ('Suspended', 'Suspended'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
    ]
