# Generated by Django 5.2.12 on 2026-03-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0023_investor_created_at_investor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='invest.marketing'),
        ),
        migrations.AddField(
            model_name='investor',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='invest.externalagent'),
        ),
    ]
