# Generated by Django 5.2.12 on 2026-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0024_investor_marketing_investor_referred_by_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='cardExpireDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='nextKycDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='suitDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
