# Generated by Django 5.2.4 on 2026-03-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0025_investor_cardexpiredate_investor_nextkycdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investor",
            name="marketing",
        ),
        migrations.RemoveField(
            model_name="investor",
            name="referred_by_agent",
        ),
    ]
