# Generated by Django 5.2.12 on 2026-03-19 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0026_remove_investor_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceprivatefundbalance',
            name='business_date_str',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancemfaccountbalance',
            name='business_date_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='performancemfaccountbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
