# Generated by Django 5.2.12 on 2026-03-20 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0027_remove_performanceprivatefundbalance_business_date_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mftransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mftransaction',
            name='transactionID',
            field=models.CharField(max_length=17),
        ),
    ]
