# Generated by Django 5.2.13 on 2026-04-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0028_mftransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoraccount',
            name='icLicense',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
