# Generated by Django 5.2.13 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0029_investoraccount_iclicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='card_number_encrypted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
