# Generated by Django 5.2.4 on 2026-03-09 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_code", models.CharField(max_length=30, unique=True)),
                ("amc_code", models.CharField(max_length=15)),
                ("fund_name_th", models.CharField(max_length=200)),
                ("fund_name_en", models.CharField(max_length=200)),
                ("fund_policy", models.TextField()),
                ("tax_type", models.CharField(blank=True, max_length=4, null=True)),
                ("fif_flag", models.BooleanField(default=False)),
                ("dividend_flag", models.BooleanField(default=False)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("fund_risk_level", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_data", models.JSONField()),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                (
                    "fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="smartNews.fund",
                    ),
                ),
            ],
        ),
    ]
