# Generated by Django 5.2.4 on 2026-04-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundProfile",
            fields=[
                (
                    "fund_code",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("amc_code", models.CharField(max_length=15)),
                ("fund_name_th", models.CharField(max_length=500)),
                ("fund_name_en", models.CharField(max_length=500)),
                ("fund_policy", models.CharField(max_length=1)),
                ("tax_type", models.CharField(blank=True, max_length=10, null=True)),
                ("fif_flag", models.CharField(max_length=1)),
                ("dividend_flag", models.CharField(max_length=1)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("fund_risk_level", models.CharField(max_length=2)),
                ("fx_risk_flag", models.CharField(max_length=1)),
                ("fatca_allow_flag", models.CharField(max_length=1)),
                ("buy_cut_off_time", models.CharField(max_length=4)),
                (
                    "fst_lowbuy_val",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "nxt_lowbuy_val",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("sell_cut_off_time", models.CharField(max_length=4)),
                (
                    "lowsell_val",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "lowsell_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "lowbal_val",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "lowbal_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("sell_settlement_day", models.IntegerField(blank=True, null=True)),
                (
                    "switching_settlement_day",
                    models.IntegerField(blank=True, null=True),
                ),
                ("switch_out_flag", models.CharField(max_length=1)),
                ("switch_in_flag", models.CharField(max_length=1)),
                ("fund_class", models.CharField(blank=True, max_length=30, null=True)),
                ("buy_period_flag", models.CharField(max_length=1)),
                ("sell_period_flag", models.CharField(max_length=1)),
                (
                    "switch_in_period_flag",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "switch_out_period_flag",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("buy_pre_order_day", models.IntegerField(blank=True, null=True)),
                ("sell_pre_order_day", models.IntegerField(blank=True, null=True)),
                ("switch_pre_order_day", models.IntegerField(blank=True, null=True)),
                (
                    "auto_redeem_fund",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("beg_ipo_date", models.DateField(blank=True, null=True)),
                ("end_ipo_date", models.DateField(blank=True, null=True)),
                ("plain_complex_fund", models.CharField(max_length=1)),
                ("derivatives_flag", models.CharField(max_length=1)),
                ("lag_allocation_day", models.IntegerField(blank=True, null=True)),
                ("settlement_holiday_flag", models.CharField(max_length=1)),
                ("health_insurance", models.CharField(max_length=1)),
                (
                    "previous_fund_code",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "investor_alert",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("isin", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "lowbal_condition",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("project_retail_type", models.CharField(max_length=1)),
                (
                    "fund_compare_performance_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("allocate_digit", models.IntegerField(blank=True, null=True)),
                ("etf_flag", models.CharField(max_length=1)),
                ("trustee", models.CharField(blank=True, max_length=1000, null=True)),
                ("registrar", models.CharField(blank=True, max_length=1000, null=True)),
                ("register_id", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "lmts_notice_period_amount",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lmts_notice_period_percent_aum",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lmts_adls_amount",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lmts_adls_percent_aum",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lmts_liquidity_fee_amount",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lmts_liquidity_fee_percent_aum",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "other_information_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "complex_fund_presentation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "risk_acknowledgement_of_complex_fund",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "redemption_type_condition",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("internal_use", models.CharField(blank=True, max_length=1, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fund Profile",
                "verbose_name_plural": "Fund Profiles",
                "db_table": "stt_fundprofile",
            },
        ),
    ]
