# Generated by Django 5.2.4 on 2026-04-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stt_fundconnext", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_code", models.CharField(max_length=30)),
                (
                    "p_ytd_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_3m_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_6m_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_1y_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_3y_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_5y_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_10y_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_si_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_1y_sd",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_3y_sd",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_5y_sd",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_10y_sd",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                ("nav_date", models.DateField()),
                (
                    "p_1m_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "p_1w_return",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "max_dd_1y",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "max_dd_3y",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "max_dd_5y",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "max_dd_10y",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fund Performance",
                "verbose_name_plural": "Fund Performances",
                "db_table": "stt_fundperformance",
                "unique_together": {("fund_code", "nav_date")},
            },
        ),
    ]
