# Generated by Django 5.2.13 on 2026-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt_fundconnext', '0002_fundperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=30)),
                ('investment_type_code', models.CharField(max_length=4)),
                ('as_end_of', models.CharField(help_text='YYYYMM', max_length=6)),
                ('investment_size', models.DecimalField(decimal_places=5, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Allocation',
                'verbose_name_plural': 'Asset Allocations',
                'db_table': 'stt_assetallocation',
                'unique_together': {('fund_code', 'investment_type_code', 'as_end_of')},
            },
        ),
    ]
