# Generated by Django 5.2.4 on 2026-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stt_fundconnext", "0003_assetallocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_code", models.CharField(max_length=30)),
                ("securities_seq", models.IntegerField()),
                ("securities_name", models.CharField(max_length=200)),
                (
                    "securities_abbreviation_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("as_end_of", models.CharField(help_text="YYYYMM", max_length=6)),
                (
                    "securities_invest_size",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Top Holding",
                "verbose_name_plural": "Top Holdings",
                "db_table": "stt_topholding",
                "unique_together": {("fund_code", "securities_seq", "as_end_of")},
            },
        ),
    ]
