# Generated by Django 5.2.4 on 2026-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stt_fundconnext", "0004_topholding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "identification_card_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "card_expiry_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "accompanying_document",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "title_other",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "en_first_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "en_last_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "th_first_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "th_last_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("birth_date", models.CharField(blank=True, max_length=20, null=True)),
                ("nationality", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("spouse", models.CharField(blank=True, max_length=200, null=True)),
                ("occupation_id", models.IntegerField(blank=True, null=True)),
                (
                    "occupation_other",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("business_type_id", models.IntegerField(blank=True, null=True)),
                (
                    "business_type_other",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "work_position",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "monthly_income_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("asset_value", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "income_source",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "income_source_other",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "income_source_country",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("related_political_person", models.BooleanField(default=False)),
                (
                    "political_related_person_position",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("can_accept_fx_risk", models.BooleanField(default=False)),
                (
                    "can_accept_derivative_investment",
                    models.BooleanField(default=False),
                ),
                ("suitability_risk_level", models.IntegerField(blank=True, null=True)),
                (
                    "suitability_evaluation_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("fatca", models.BooleanField(default=False)),
                (
                    "fatca_declaration_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cdd_score", models.IntegerField(blank=True, null=True)),
                ("cdd_date", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "referral_person",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "application_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "accepted_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "open_fund_connext_form_flag",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "approved_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "approved_date_time",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "open_channel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "investor_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vulnerable_flag", models.BooleanField(default=False)),
                ("vulnerable_detail", models.TextField(blank=True, null=True)),
                ("ndid_flag", models.BooleanField(default=False)),
                (
                    "ndid_request_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "investor_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("knowledge_assessment_result", models.BooleanField(default=False)),
                (
                    "profile_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "crs_place_of_birth_country",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "crs_place_of_birth_city",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "crs_tax_residence_in_countries_other_than_the_us",
                    models.BooleanField(default=False),
                ),
                (
                    "crs_declaration_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "identity_verification_date_time",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "dopa_verification_date_time",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_address_same_as_flag",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("identification_document", models.JSONField(blank=True, null=True)),
                ("current_address", models.JSONField(blank=True, null=True)),
                ("work_address", models.JSONField(blank=True, null=True)),
                ("suitability_form", models.JSONField(blank=True, null=True)),
                ("knowledge_assessment_form", models.JSONField(blank=True, null=True)),
                ("crs_details", models.JSONField(blank=True, null=True)),
                ("accounts", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Individual",
                "verbose_name_plural": "Customer Individuals",
                "db_table": "stt_customer_individual",
            },
        ),
    ]
