"""PDF export for the IT Request workflow (WorkflowConfig.category == 'IT').

Layout is modeled on the paper "IT REQUEST" form (Merchant Partners Securities):
subject checkboxes, requestor info, priority, description, and an approval
process table (step / approver / action / date / comment) built from
ApprovalLog. Other workflow categories are not covered by this module —
each workflow category is expected to get its own template as needed.
"""
import io
import logging
import os

from django.conf import settings
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

logger = logging.getLogger(__name__)

# fonts-thai-tlwg (installed at the OS level, see backend/Dockerfile) ships Garuda
# under this path on Debian/Ubuntu. ReportLab's base14 fonts are Latin-only, so
# without this, any Thai text (subject names, comments, descriptions) renders blank.
_THAI_FONT_DIR = "/usr/share/fonts/truetype/tlwg"
_THAI_FONT_REGULAR = "Garuda"
_THAI_FONT_BOLD = "Garuda-Bold"

_font_registered = False


def _ensure_thai_font():
    """Register the Thai-capable Garuda font, falling back to Helvetica if unavailable
    (e.g. running outside the Docker image where fonts-thai-tlwg isn't installed)."""
    global _font_registered
    if _font_registered:
        return

    try:
        pdfmetrics.registerFont(TTFont(_THAI_FONT_REGULAR, os.path.join(_THAI_FONT_DIR, "Garuda.ttf")))
        pdfmetrics.registerFont(TTFont(_THAI_FONT_BOLD, os.path.join(_THAI_FONT_DIR, "Garuda-Bold.ttf")))
        pdfmetrics.registerFontFamily(
            _THAI_FONT_REGULAR, normal=_THAI_FONT_REGULAR, bold=_THAI_FONT_BOLD,
            italic=_THAI_FONT_REGULAR, boldItalic=_THAI_FONT_BOLD,
        )
    except Exception as e:
        logger.warning(f"Thai font registration failed, falling back to Helvetica: {e}")
        globals()["_THAI_FONT_REGULAR"] = "Helvetica"
        globals()["_THAI_FONT_BOLD"] = "Helvetica-Bold"

    _font_registered = True


PRIORITY_LABELS = {1: "High", 2: "Medium", 3: "Low"}


def generate_it_request_pdf(request_obj, exported_by=None) -> io.BytesIO:
    """Build the IT Request PDF for a workflow `Request` instance and return a
    seeked-to-0 BytesIO buffer ready for FileResponse.

    `exported_by`: the Django User who triggered the export (shown in the
    footer as "Generated by <user>"). Falls back to "xInvest" if not passed.
    """
    _ensure_thai_font()

    styles = getSampleStyleSheet()
    body = ParagraphStyle(
        "body", parent=styles["Normal"], fontName=_THAI_FONT_REGULAR, fontSize=9, leading=12,
    )
    label_bold = ParagraphStyle(
        "labelBold", parent=body, fontName=_THAI_FONT_BOLD,
    )
    title_style = ParagraphStyle(
        "title", parent=styles["Title"], fontName=_THAI_FONT_BOLD, fontSize=18, alignment=1,
    )
    section_style = ParagraphStyle(
        "section", parent=label_bold, fontSize=10, spaceBefore=8, spaceAfter=4,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=15 * mm, bottomMargin=15 * mm, leftMargin=15 * mm, rightMargin=15 * mm,
    )
    elements = []

    # --- Company letterhead (optional, configured via PDF_COMPANY_NAME /
    # PDF_COMPANY_ADDRESS / PDF_LOGO_PATH settings — see core/settings.py) ---
    company_block = _build_company_letterhead(body, label_bold)
    if company_block:
        elements.append(company_block)
        elements.append(Spacer(1, 6))

    # --- Header ---
    elements.append(Paragraph("IT REQUEST", title_style))
    elements.append(Spacer(1, 2))
    # elements.append(Paragraph(request_obj.title, ParagraphStyle(
    #     "subtitle", parent=body, fontName=_THAI_FONT_BOLD, fontSize=11, alignment=1,
    # )))
    # elements.append(Spacer(1, 4))
    # elements.append(Paragraph("Information", section_style))

    creator_name = request_obj.creator.get_full_name() or request_obj.creator.username
    priority_label = PRIORITY_LABELS.get(request_obj.priorify, "-")
    header_table = Table(
        [[
            Paragraph(f"<b>Registered No.:</b> {request_obj.req_code or request_obj.id}", body),
            Paragraph(f"<b>Create Date:</b> {timezone.localtime(request_obj.created_at).strftime('%d/%m/%Y')}", body),
        ],
        [Paragraph(f"<b>Requestor's Name:</b> {creator_name}", body),
             Paragraph(f"<b>Department:</b> {request_obj.create_department or '-'}", body)],
            [Paragraph(f"<b>Priority:</b> {priority_label}", body),
             Paragraph(
                 f"<b>Target Date:</b> {request_obj.expectDate.strftime('%d/%m/%Y') if request_obj.expectDate else '-'}",
                 body,
             )],
        
        ],
        colWidths=[None, None],
    )
    header_table.setStyle(TableStyle([("ALIGN", (1, 0), (1, 0), "RIGHT")]))
    elements.append(header_table)
    elements.append(Spacer(1, 10))

    # --- Subject ---
    # Plain label list of the request's actual selected subjects — no fixed
    # checkbox grid, since the configured RequestSubject names are workflow-specific
    # and won't line up with any hardcoded set of labels.
    # elements.append(Spacer(1, 12))
    elements.append(Paragraph("Title", section_style))
    elements.append(Paragraph(request_obj.title,body))

    
    elements.append(Paragraph("Subject", section_style))
    subject_names = [s["name"] for s in _get_subjects(request_obj)]
    elements.append(Paragraph(", ".join(subject_names) if subject_names else "-", body))


    # --- Description ---
    elements.append(Paragraph("Description", section_style))
    desc_table = Table(
        [[Paragraph(request_obj.description or "-", body)]],
        colWidths=[180 * mm],
    )
    desc_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(desc_table)

    # --- Approval process ---
    elements.append(Paragraph("Approval Process", section_style))
    logs_by_step = {}
    for log in request_obj.logs.all().order_by("created_at"):
        logs_by_step.setdefault(log.step_number, log)  # first log per step (the decision made at that step)

    approval_rows = [["No.", "Step", "Approver", "Action", "Date / Time", "Comment"]]
    steps = list(request_obj.workflow.steps.all().order_by("step_number"))
    for step in steps:
        log = logs_by_step.get(step.step_number)
        if log:
            approver_name = log.approver.get_full_name() or log.approver.username if log.approver else "-"
            action_label = dict(log.__class__.ACTION_CHOICES).get(log.action, log.action)
            log_date = timezone.localtime(log.created_at).strftime("%d/%m/%Y %H:%M")
            comment = log.comment or "-"
        else:
            # Not yet acted upon — show who is expected to approve this step.
            if step.is_department_manager:
                expected = "Department Manager"
            elif step.required_group:
                expected = step.required_group.name
            else:
                expected = "-"
            approver_name = expected
            action_label = "Pending"
            log_date = "-"
            comment = "-"
        approval_rows.append([
            Paragraph(str(step.step_number), body),
            Paragraph(step.step_name, body),
            Paragraph(approver_name, body),
            Paragraph(action_label, body),
            Paragraph(log_date, body),
            Paragraph(comment, body),
        ])

    approval_table = Table(
        approval_rows,
        colWidths=[10 * mm, 30 * mm, 30 * mm, 20 * mm, 30 * mm, 60 * mm],
        repeatRows=1,
    )
    approval_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), _THAI_FONT_BOLD),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(approval_table)

    # --- Requestor rating (given after completion, if any) ---
    if request_obj.rating is not None:
        elements.append(Paragraph("Requestor Rating", section_style))
        elements.append(Paragraph(f"<b>Score:</b> {request_obj.rating} / 5", body))
        if request_obj.rating_comment:
            elements.append(Paragraph(f"<b>Comment:</b> {request_obj.rating_comment}", body))

    # --- Footer ---
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(
        f"<b>Status:</b> {request_obj.get_status_display()}"
        + (f" &nbsp;&nbsp; <b>Completed:</b> {timezone.localtime(request_obj.completed_at).strftime('%d/%m/%Y %H:%M')}"
           if request_obj.completed_at else ""),
        body,
    ))
    elements.append(Spacer(1, 4))
    exported_by_name = "xInvest"
    if exported_by is not None:
        exported_by_name = exported_by.get_full_name() or exported_by.username
    elements.append(Paragraph(
        f"Generated by {exported_by_name} on {timezone.localtime(timezone.now()).strftime('%d/%m/%Y %H:%M')}",
        ParagraphStyle("footer", parent=body, fontSize=7, textColor=colors.grey),
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def _get_subjects(request_obj):
    return [{"name": s.name} for s in request_obj.reqSubject.all()]


def _build_company_letterhead(body, label_bold):
    """Build the optional logo + company name/address header block.
    Returns None if nothing is configured (PDF_COMPANY_NAME / PDF_LOGO_PATH
    in core/settings.py, set via env vars — no code change needed to update)."""
    company_name = getattr(settings, "PDF_COMPANY_NAME", "")
    company_address = getattr(settings, "PDF_COMPANY_ADDRESS", "")
    logo_path = getattr(settings, "PDF_LOGO_PATH", "")

    logo_cell = ""
    if logo_path:
        if os.path.exists(logo_path):
            try:
                logo_cell = Image(logo_path, width=30 * mm, height=30 * mm, kind="proportional")
            except Exception as e:
                logger.warning(f"Failed to load PDF_LOGO_PATH image '{logo_path}': {e}")
        else:
            logger.warning(f"PDF_LOGO_PATH is set but file not found: {logo_path}")

    text_lines = []
    if company_name:
        text_lines.append(Paragraph(company_name, label_bold))
    if company_address:
        for line in company_address.split("\n"):
            text_lines.append(Paragraph(line, body))

    if not logo_cell and not text_lines:
        return None

    table = Table([[logo_cell, text_lines]], colWidths=[35 * mm, 145 * mm])
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (0, 0), 0),
    ]))
    return table
