# Generated by Django 5.2.15 on 2026-07-10 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_profile_is_email_verified_profile_mobile_number'),
        ('workflow', '0007_request_auditflag_request_expectdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('EXPORTED', 'EXPORTED'), ('CONFIRMED', 'CONFIRMED')], default='DRAFT', max_length=20)),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='payment/batches/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PVNumberingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='PV', max_length=10)),
                ('pattern', models.CharField(default='{prefix}{seq:02d}/{running:03d}', max_length=100)),
                ('reset_period', models.CharField(choices=[('NEVER', 'NEVER'), ('YEARLY', 'YEARLY'), ('MONTHLY', 'MONTHLY')], default='YEARLY', max_length=10)),
                ('current_seq', models.PositiveIntegerField(default=1)),
                ('current_running', models.PositiveIntegerField(default=0)),
                ('last_reset_period_key', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(db_index=True, max_length=13, unique=True)),
                ('branch_type', models.CharField(choices=[('HQ', 'สำนักงานใหญ่'), ('BRANCH', 'สาขา')], default='HQ', max_length=10)),
                ('branch_no', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('default_wht_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentApprovalTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflowconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('invoice_no_ref', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_fixed_asset', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RETURNED', 'RETURNED'), ('PAID', 'PAID')], default='DRAFT', max_length=20)),
                ('pay_bank', models.CharField(blank=True, max_length=100)),
                ('cheque_no', models.CharField(blank=True, max_length=50)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='payment.paymentbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_voucher', to='workflow.request')),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('VEHICLE', 'ยานพาหนะ'), ('COMPUTER', 'คอมพิวเตอร์'), ('FURNITURE', 'เครื่องตกแต่ง/เครื่องมือเครื่องใช้'), ('OFFICE_DECOR', 'ค่าตกแต่งสำนักงาน'), ('SOFTWARE', 'ซอฟต์แวร์คอมพิวเตอร์'), ('OTHER', 'อื่นๆ')], max_length=20)),
                ('legacy_pv_ref', models.CharField(blank=True, max_length=50)),
                ('tax_invoice_no', models.CharField(blank=True, max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchase_date', models.DateField()),
                ('depreciation_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('useful_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('disposed_at', models.DateField(blank=True, null=True)),
                ('purchase_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wht_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.department')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payment.paymentvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('QUOTATION', 'ใบเสนอราคา'), ('INVOICE', 'ใบแจ้งหนี้/บิล')], max_length=20)),
                ('file', models.FileField(upload_to='payment/documents/%Y/%m/%d/')),
                ('extraction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('NEEDS_REVIEW', 'NEEDS_REVIEW')], default='PENDING', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('ai_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_invoices', to='payment.sourcedocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier_guess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.sourcedocument'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('account_no', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=255)),
                ('is_current', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='payment.supplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='payee_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.supplierbankaccount'),
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('accumulated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_disallowed_expense', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='payment.fixedasset')),
            ],
            options={
                'unique_together': {('asset', 'period')},
            },
        ),
        migrations.AddConstraint(
            model_name='supplierbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('supplier',), name='one_current_bank_account_per_supplier'),
        ),
    ]
