# Generated by Django 5.2.12 on 2026-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_requestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='create_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
