# Generated by Django 5.2.4 on 2026-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_request_create_department_request_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="is_department_manager",
            field=models.BooleanField(
                default=False, verbose_name="เป็นหัวหน้าแผนกของผู้สร้าง"
            ),
        ),
    ]
