# Generated by Django 5.2.4 on 2026-03-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_workflowstep_is_department_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="req_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workflowconfig",
            name="prefix",
            field=models.CharField(
                default="REQ", max_length=10, verbose_name="รหัสเรียกหน้าชื่อ"
            ),
        ),
    ]
