# Generated by Django 5.2.15 on 2026-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_request_req_code_workflowconfig_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
