# Generated by Django 5.2.15 on 2026-06-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_requestfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='auditFlag',
            field=models.BooleanField(default=False, verbose_name='Audit Flag'),
        ),
        migrations.AddField(
            model_name='request',
            name='expectDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Completion Date'),
        ),
        migrations.AddField(
            model_name='request',
            name='priorify',
            field=models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, verbose_name='Priority'),
        ),
        migrations.CreateModel(
            name='RequestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='workflow.workflowconfig', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Request Subject',
                'verbose_name_plural': 'Request Subjects',
                'ordering': ['order', 'name'],
                'unique_together': {('workflow', 'code')},
            },
        ),
        migrations.AddField(
            model_name='request',
            name='reqSubject',
            field=models.ManyToManyField(blank=True, related_name='requests', to='workflow.requestsubject', verbose_name='Subject(s)'),
        ),
    ]
