# Generated by Django 5.2.12 on 2026-03-06 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='otp_code',
        ),
        migrations.AddField(
            model_name='otp',
            name='max_otp_try',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_ref',
            field=models.CharField(default="", max_length=6),
            preserve_default=False,
        ),
    ]
