# Generated by Django 5.2.12 on 2026-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_code_otp_otp_code_otp_max_otp_try_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otpSuccess_DT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
