# Generated by Django 5.2.12 on 2026-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_department_alter_profile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
